### ISSUE TITLE
Spamsum similarity score issue

### ISSUE THREAD

**Issue by paz-csis** [freakboy3742/pyspamsum#4]
Hi,

First, thanks a lot for that great tool :slightly_smiling_face: 

We just ran into a weird problem, I think the code is more explanatory than words:
```
>>> import spamsum
>>> f = open('somefile', mode='r')
>>> html = f.read()
>>> c1 = spamsum.spamsum(html)
>>> c1
'96:q66666666666666666666666666666666666666666666666666666666666666I:N'
>>> spamsum.match(c1, c1)
0
```

Basically, we found some spamsums that had a score of 0 for themselves. An other tool like `ssdeep` gave us a score of 100 on that one, so not sure what's happening?

(snippet of the ssdeep code below:
```
>>> import ssdeep
>>> f = open('somefile', 'r')
>>> html = f.read()
>>> c1 = ssdeep.hash(html)
>>> c1
'96:q66666666666666666666666666666666666666666666666666666666666666I:N'
>>> ssdeep.compare(c1, c1)
100
```
)

**Comment by paz-csis** [comment]
Alright, actually the root cause is in the function `has_common_spamsum`, which seems not to work when you have two strings that are 6 chars or less:
```
int main(void) {
    printf("%d\n", has_common_substring("coucou", "coucou"));
    printf("%d\n", has_common_substring("coucouuuu", "coucouuuuu"));
}
```
```
pyspamsum $ ./test
0
1
```
Here's the culprit: https://github.com/freakboy3742/pyspamsum/blob/master/spamsum.c#L267
`if (i < ROLLING_WINDOW-1) continue;`

I can submit a PR, just not sure how you'd like me to fix it - we could check at the end of that function if the length is less than 6, and then do `strstr(s1, s2); strstr(s2, s1)` to check if one is a substring of the other. But that seems awfully specific...

**Comment by freakboy3742** [comment]
Thanks for the report. This project was purely intended as a wrapper around [Andrew Tridgell's spamsum](https://github.com/tridge/junkcode/tree/master/spamsum) implementation. If there are flaws in the algorithm, they should be reported (and fixed) there.

If there's a change in Andrew's implementation (it hasn't changed in 13 years), I'm happy to integrate that change into pyspamsum.
